__default__:
    partition: "shared"
    time: 720
    nodes: 1
    output: "logs/slurm-%j.out"
    error: "logs/slurm-%j.err"


#############
# stringtie #
############


fastqc:
    partition: "serial_requeue,shared" 
    output: "logs/fastqc-%j.out"
    error: "logs/fastqc-%j.err"
    job-name: "fastqc"

trimgalore:
    partition: "serial_requeue,shared"
    output: "logs/trimgalore-%j.out"
    error: "logs/trimgalore-%j.err"
    job-name: "tgalore"

filter_rna:
    partition: "serial_requeue,shared"
    output: "logs/filterrna-%j.out"
    error: "logs/filterrna-%j.err"
    job-name: "filtrna"

filter_chloroplast_mt_rna:
    partition: "serial_requeue,shared"
    output: "logs/filter_cholplast-mtRNA-%j.out"
    error: "logs/filter_cholplast-mtRNA-%j.err"
    job-name: "filtchlorMT"

cluster:
    partition: "serial_requeue,shared"
    output: "logs/cluster-%j.out"
    error: "logs/cluster-%j.err"
    job-name: "cluster"

split_by_sample:
    partition: "serial_requeue,shared"
    output: "logs/splitbysample-%j.out"
    error: "logs/splitbysample-%j.err"
    job-name: "splitbysamp"

convert_1:
    partition: "serial_requeue,shared"
    output: "logs/convert1-%j.out"
    error: "logs/convert1-%j.err"
    job-name: "convert1"

convert_2:
    partition: "serial_requeue,shared"
    output: "logs/convert2-%j.out"
    error: "logs/convert2-%j.err"
    job-name: "convert2"

retrieve_encoding_quality:
    partition: "serial_requeue,shared"
    output: "logs/retrieve-encod-qual-%j.out"
    error: "logs/retrieve-encod-qual-%j.err"
    job-name: "getencodqual"

log_lengths_end:
    partition: "serial_requeue,shared"
    output: "logs/log-lengths-end-%j.out"
    error: "logs/log-lengths-end-%j.err"
    job-name: "loglengthsend"

size_profiles:
    partition: "serial_requeue,shared"
    output: "logs/sizeprofiles-%j.out"
    error: "logs/sizeprofiles-%j.err"
    job-name: "sizeprofiles"
